#!/usr/bin/env bash
set -euo pipefail

# Resolve paths from the script location so the script works from any cwd.
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
GEMM_DIR="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd -- "${GEMM_DIR}/../.." && pwd)"
BUILD_DIR="${GEMM_DIR}/build"

# Defaults can be overridden with environment variables.
NCU_BIN="${NCU_BIN:-ncu}"
BENCH="${BENCH:-${BUILD_DIR}/bench_gemm}"
OUT_DIR="${OUT_DIR:-${GEMM_DIR}/profile_results/$(date +%Y%m%d_%H%M%S)}"
METRICS_FILE="${METRICS_FILE:-${REPO_ROOT}/tools/gemm_metrics.txt}"
LAUNCH_SKIP="${LAUNCH_SKIP:-1}"
LAUNCH_COUNT="${LAUNCH_COUNT:-1}"
ITERS="${ITERS:-3}"
ANALYZE="${ANALYZE:-1}"
MODE="${MODE:-kernel}"

usage() {
  cat <<EOF
Usage: $(basename "$0")

Profile GEMM benchmark shapes/algorithms with Nsight Compute.

Environment overrides:
  BUILD=1                  Build bench_gemm before profiling.
  NCU_BIN=path             Nsight Compute executable. Default: ncu
  BENCH=path               Benchmark binary. Default: ${BUILD_DIR}/bench_gemm
  OUT_DIR=path             Output directory. Default: timestamped profile_results dir
  METRICS_FILE=path        Metric list. Default: ${METRICS_FILE}
  MODE=kernel|shape        kernel: fixed algorithm over SHAPES.
                           shape: fixed SHAPE over ALGORITHMS.
                           Default: ${MODE}
  ALGORITHM=name           Algorithm for MODE=kernel. Default: NAIVE
  ALGORITHMS="..."         Space-separated algorithms for MODE=shape.
                           Default: hand-written kernels with known names.
  SHAPE="M N K"            Fixed shape for MODE=shape. Default: "1024 1024 1024"
  SHAPES="M N K;..."       Semicolon-separated shapes.
                           Default: "1024 1024 1024;2048 2048 2048;4096 4096 4096"
  ITERS=n                  Benchmark iterations per ncu run. Default: ${ITERS}
  LAUNCH_SKIP=n            Matching launches to skip. Default: ${LAUNCH_SKIP}
                           Default skips bench_gemm's warmup launch.
  LAUNCH_COUNT=n           Matching launches to profile. Default: ${LAUNCH_COUNT}
  ANALYZE=0                Skip merged_metrics.csv generation.

Outputs:
  summary.tsv              Per-algorithm/shape index of generated files.
  merged_metrics.csv       Metric summary generated by tools/analyze_gemm.py when ANALYZE=1.
  *.ncu-rep                Nsight Compute reports.
  *.raw.csv                Vertical CSV: section,name,unit,value.
  *.ncu.log                Nsight Compute logs.
  *.stdout.log             Benchmark stdout.
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

ALGORITHM="${ALGORITHM:-${KERNEL_ALGO:-NAIVE}}"
ALGORITHMS="${ALGORITHMS:-NAIVE SHARED_MEM REGISTER VECTORIZED DOUBLE_BUF TENSOR_CORE ULTIMATE }"
SHAPE="${SHAPE:-1024 1024 1024}"
SHAPES="${SHAPES:-1024 1024 1024;2048 2048 2048;4096 4096 4096}"

kernel_for_algo() {
  case "$1" in
    NAIVE) echo "gemm_naive_kernel" ;;
    SHARED_MEM|SHARED_MEMORY|SHARED) echo "gemm_shared_kernel" ;;
    REGISTER) echo "gemm_register_kernel" ;;
    VECTORIZED|VECTOR) echo "gemm_vectorized_kernel" ;;
    DOUBLE_BUF|DOUBLE_BUFFERED|BUFFER) echo "gemm_double_buffered_kernel" ;;
    TENSOR_CORE|TENSOR) echo "gemm_tensor_core_kernel" ;;
    ASYNC) echo "gemm_async_kernel" ;;
    ULTIMATE) echo "gemm_ultimate_kernel" ;;
    ZHIHU) echo "doublebufferingGEMM" ;;
    *)
      echo "unsupported algorithm: $1" >&2
      return 1
      ;;
  esac
}

canonical_algo() {
  case "$1" in
    NAIVE) echo "NAIVE" ;;
    SHARED_MEM|SHARED_MEMORY|SHARED) echo "SHARED_MEM" ;;
    REGISTER) echo "REGISTER" ;;
    VECTORIZED|VECTOR) echo "VECTORIZED" ;;
    DOUBLE_BUF|DOUBLE_BUFFERED|BUFFER) echo "DOUBLE_BUF" ;;
    TENSOR_CORE|TENSOR) echo "TENSOR_CORE" ;;
    ASYNC) echo "ASYNC" ;;
    ULTIMATE) echo "ULTIMATE" ;;
    ZHIHU) echo "ZHIHU" ;;
    *)
      echo "unsupported algorithm: $1" >&2
      return 1
      ;;
  esac
}

sanitize() {
  printf '%s' "$1" | tr '[:lower:]' '[:upper:]' | tr -c 'A-Z0-9_' '_'
}

# Optional one-shot build: BUILD=1 kernels/gemm/scripts/profile.sh
if [[ "${BUILD:-0}" == "1" ]]; then
  cmake -S "${GEMM_DIR}" -B "${BUILD_DIR}"
  cmake --build "${BUILD_DIR}" --target bench_gemm -j
fi

if [[ ! -x "${BENCH}" ]]; then
  echo "missing benchmark: ${BENCH}" >&2
  echo "run: BUILD=1 $0" >&2
  exit 1
fi

# Strip comments/blank lines and pass metrics to ncu as a comma-separated list.
METRICS="$(
  sed 's/#.*//; /^[[:space:]]*$/d; s/^[[:space:]]*//; s/[[:space:]]*$//' "${METRICS_FILE}" |
    paste -sd, -
)"

# Convert ncu's wide raw CSV into a stable section/name/unit/value layout.
csv_to_vertical() {
  python3 - "$1" "$2" "$3" <<'PY'
import csv
import sys

src, dst, metrics_file = sys.argv[1], sys.argv[2], sys.argv[3]

metric_order = []
metric_sections = {}
current_section = "metrics"

with open(metrics_file) as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        if line.startswith("#"):
            tag = "# section:"
            if line.lower().startswith(tag):
                current_section = line[len(tag):].strip()
            continue
        metric = line.split("#", 1)[0].strip()
        if metric:
            metric_order.append(metric)
            metric_sections[metric] = current_section

with open(src, newline="") as f:
    rows = list(csv.reader(f))

if len(rows) < 3:
    raise SystemExit(f"unexpected csv format: {src}")

headers, units, values = rows[:3]
by_name = {
    name: (unit, value)
    for name, unit, value in zip(headers, units, values)
    if name and value != ""
}

context_names = [
    "ID",
    "Process ID",
    "Process Name",
    "Kernel Name",
    "Block Size",
    "Grid Size",
    "Device",
    "CC",
]

with open(dst, "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(["section", "name", "unit", "value"])

    for name in context_names:
        if name in by_name:
            unit, value = by_name[name]
            writer.writerow(["context", name, unit, value])

    for name in metric_order:
        if name not in by_name:
            continue
        unit, value = by_name[name]
        writer.writerow([metric_sections[name], name, unit, value])
PY
}

mkdir -p "${OUT_DIR}"
SUMMARY="${OUT_DIR}/summary.tsv"
echo -e "algo\tkernel\tM\tN\tK\treport\traw_csv\tlog\tstdout" > "${SUMMARY}"

echo "out: ${OUT_DIR}"
echo "bench: ${BENCH}"
echo "mode: ${MODE}"
echo "launch skip/count: ${LAUNCH_SKIP}/${LAUNCH_COUNT}"

declare -a RUN_ALGOS
declare -a RUN_SHAPES

case "${MODE}" in
  kernel|shape_sweep|shapes)
    RUN_ALGOS=("$(canonical_algo "${ALGORITHM}")")
    IFS=';' read -r -a RUN_SHAPES <<< "${SHAPES}"
    echo "algorithm: ${RUN_ALGOS[*]}"
    echo "shapes: ${SHAPES}"
    ;;
  shape|algo_sweep|algorithms)
    RUN_SHAPES=("${SHAPE}")
    for algo in ${ALGORITHMS}; do
      RUN_ALGOS+=("$(canonical_algo "${algo}")")
    done
    echo "shape: ${SHAPE}"
    echo "algorithms: ${RUN_ALGOS[*]}"
    ;;
  *)
    echo "unsupported MODE: ${MODE}" >&2
    echo "use MODE=kernel or MODE=shape" >&2
    exit 1
    ;;
esac

for algo in "${RUN_ALGOS[@]}"; do
  KERNEL="$(kernel_for_algo "${algo}")"
  SAFE_ALGO="$(sanitize "${algo}")"

  for shape in "${RUN_SHAPES[@]}"; do
    read -r M N K <<< "${shape}"
    if [[ -z "${M:-}" || -z "${N:-}" || -z "${K:-}" ]]; then
      echo "invalid GEMM shape: ${shape}" >&2
      exit 1
    fi
    PREFIX="${OUT_DIR}/${SAFE_ALGO}_M${M}_N${N}_K${K}"
    REPORT="${PREFIX}.ncu-rep"
    WIDE_CSV="${PREFIX}.wide.csv"
    RAW_CSV="${PREFIX}.raw.csv"
    LOG="${PREFIX}.ncu.log"
    STDOUT="${PREFIX}.stdout.log"

    echo "profile algo=${algo} kernel=${KERNEL} M=${M} N=${N} K=${K}"

    "${NCU_BIN}" \
      --force-overwrite \
      --target-processes application-only \
      --kernel-name-base function \
      --kernel-name "${KERNEL}" \
      --launch-skip "${LAUNCH_SKIP}" \
      --launch-count "${LAUNCH_COUNT}" \
      --disable-extra-suffixes \
      --metrics "${METRICS}" \
      --export "${REPORT}" \
      --log-file "${LOG}" \
      "${BENCH}" "${M}" "${N}" "${K}" "${algo}" "${ITERS}" \
      > "${STDOUT}"

    "${NCU_BIN}" \
      --import "${REPORT}" \
      --page raw \
      --csv \
      --log-file "${WIDE_CSV}" \
      >/dev/null

    csv_to_vertical "${WIDE_CSV}" "${RAW_CSV}" "${METRICS_FILE}"
    rm -f "${WIDE_CSV}"

    echo -e "${algo}\t${KERNEL}\t${M}\t${N}\t${K}\t${REPORT}\t${RAW_CSV}\t${LOG}\t${STDOUT}" >> "${SUMMARY}"
  done
done

if [[ "${ANALYZE}" == "1" ]]; then
  python3 "${REPO_ROOT}/tools/analyze_gemm.py" --dir "${OUT_DIR}"
fi

echo "done: ${SUMMARY}"
